stages:
  - build

build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/odboy/devops:kenaito-nodejs-18.20.8
  tags:
    - builder
  only:
    - api
  before_script:
    - node -v
  script:
    - pwd
