stages:
  - build

build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/odboy/devops:kenaito-nodejs-14.21.3
  tags:
    - builder
  before_script:
    - node -v
  script:
    - pwd
  only:
    - api
