stages:
  - build

build:
  stage: build
  image: registry.cn-shanghai.aliyuncs.com/odboy/devops:kenaito-python-3.13.7
  tags:
    - builder
  only:
    - api
  before_script:
    - python3 -V
  script:
    - pwd
